FROM node:alpine

# Also exposing VSCode debug ports
EXPOSE 8000 9929 9230 3000

RUN \
  apk add --no-cache python make g++ && \
  apk add vips-dev fftw-dev --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/community --repository http://dl-3.alpinelinux.org/alpine/edge/main && \
  rm -fR /var/cache/apk/*

RUN npm install -g create-react-app yarn tslint typescript tslint-react prettier

WORKDIR /app
COPY ./package.json .
COPY ./yarn.lock .
# RUN yarn install && yarn cache clean
RUN yarn install
# COPY . .
CMD ["yarn", "start"]
